[theme]
base = "dark"
primaryColor = "#63d9d1"
backgroundColor = "#080d16"
secondaryBackgroundColor = "#0e1623"
textColor = "#edf3fa"
font = "sans serif"

[server]
address = "127.0.0.1"
port = 8501
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 50
maxMessageSize = 50
headless = true

[browser]
serverAddress = "127.0.0.1"
gatherUsageStats = false
